### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by wangzhen5201314** [MAS0NM/tooth_seg#1]
![image](https://user-images.githubusercontent.com/81815940/231419424-d95eccaf-0ee7-47e6-b8ba-79dd842802eb.png)

I want to ask, what is the pygco in the picture. What type of file format is it? I remember pygco was a library

**Comment by wangzhen5201314** [comment]
in infer.py

**Comment by MAS0NM** [comment]
> ![image](https://user-images.githubusercontent.com/81815940/231419424-d95eccaf-0ee7-47e6-b8ba-79dd842802eb.png)
> 
> I want to ask, what is the pygco in the picture. What type of file format is it? I remember pygco was a library

This parameter decides whether to use pygco.cut_from_graph() function to refine the raw output of the network, which will be passed to the 4th parameter of function infer().

Hope this helps you well.

**Comment by wangzhen5201314** [comment]
Thank you for coming back. This is useful to me. Thank you very much
