### ISSUE TITLE
how to create json file

### ISSUE THREAD

**Issue by gxu12** [MAS0NM/tooth_seg#2]
Hi,
Is there any way or standard to get the json files under dataset folder?
Thank you!

**Comment by MAS0NM** [comment]
Sry for the late reply
The json files in dataset are provided by my colleagues together with the mesh files
I'm not sure if they're along with a public dataset or manually annotated afterwards
But I believe this dataset is from MICCAI challenge
Plz take a look at MICCAI challenge website to see if there are any related things
Hope this finds you well
