### ISSUE TITLE
Update train_lit.py file according to newer pytorch version

### ISSUE THREAD

**Issue by RutujaSpirangle** [MAS0NM/tooth_seg#3]
Can i get the updated version of the train_lit.py file. As far as i understand this is supporting older version of pytorch lightning.It would great help if i get the updated code which supports pytorch version 2.2.2

**Comment by MAS0NM** [comment]
I'm no longer working on this project ever since the last submit, sry for that.
Perhaps you can try chatGPT if ur having trouble figuring out the version diferences, it won't be too many changes in code I believe.
Good luck!
